### ISSUE TITLE
Crash rendering entity

### ISSUE THREAD

**Issue by FeSong** [SaemonMoki/ExtendedAnimals#31]
Seems to be the only mod causing errors for me in the modlist.
Also I have a server with 4 other friends running with these mods and they have no issues :/ I have higher specs than all of them yet I can't render the entities lol here is log:

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 27/04/20 06:45
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at mokiyoki.enhancedanimals.model.ModelEnhancedPig.setLivingAnimations(ModelEnhancedPig.java:249) ~[?:0_5_1] {re:classloading,pl:runtimedistcleaner:A}
	at mokiyoki.enhancedanimals.model.ModelEnhancedPig.func_212843_a_(ModelEnhancedPig.java:19) ~[?:0_5_1] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:110) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(SourceFile:43) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:245) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1094) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:948) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:422) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.50.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$422/1800959603.call(Unknown Source) [forge-1.15.2-31.1.50.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mokiyoki.enhancedanimals.model.ModelEnhancedPig.setLivingAnimations(ModelEnhancedPig.java:249)
	at mokiyoki.enhancedanimals.model.ModelEnhancedPig.func_212843_a_(ModelEnhancedPig.java:19)
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:110)
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(SourceFile:43)
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(SourceFile:18)

-- Entity being rendered --
Details:
	Entity Type: eanimod:enhanced_pig (mokiyoki.enhancedanimals.entity.EnhancedPig)
	Entity ID: 3560
	Entity Name: Pig
	Entity's Exact location: -192.18, 69.00, 15.30
	Entity's Block location: World: (-193,69,15), Chunk: (at 15,4,15 in -13,0; contains blocks -208,0,0 to -193,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: mokiyoki.enhancedanimals.renderer.RenderEnhancedPig@6c18bbf1
	Location: -79.94,1.38,16.48 - World: (-80,1,16), Chunk: (at 0,0,0 in -5,1; contains blocks -80,0,16 to -65,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: 56.25
	Delta: 0.120025635
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:245)
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1094)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:948)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600)

-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['shifty333'/7468, l='MpServer', x=-112.30, y=66.00, z=-1.18], RemoteClientPlayerEntity['karumasin'/446, l='MpServer', x=-72.01, y=64.00, z=-153.11]]
	Chunk stats: Client Chunk Cache: 729, 492
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -7724184020907872652
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (128,64,-207), Chunk: (at 0,4,1 in 8,-13; contains blocks 128,0,-208 to 143,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 40007 game time, 40007 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:568)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$422/1800959603.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3440118720 bytes (3280 MB) / 8489271296 bytes (8096 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.1.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.50.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.50.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.50.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.50.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.50.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.50
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.50-client.jar Minecraft {minecraft@1.15.2 DONE}
		industrial-foregoing-1.15.2-2.2.2-28d4a81.jar Industrial Foregoing {industrialforegoing@2.2.2 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		titanium-1.15.2-2.3.7.jar Titanium {titanium@2.3.7 DONE}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		valhelsia_structures-15.0.2a.jar Valhelsia Structures {valhelsia_structures@15.0.2a DONE}
		jei-1.15.2-6.0.0.3.jar Just Enough Items {jei@6.0.0.3 DONE}
		worleycaves-1.15.2-1.6.0.jar Worley's Caves {worleycaves@1.15.2-1.6.0 DONE}
		simplefarming-1.15.2-1.2.7.jar Simple Farming {simplefarming@1.15.2-1.2.7 DONE}
		GeneticAnimals-0_5_1.jar Genetic Animals {eanimod@0_5_1 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		Mekanism-1.15.2-9.10.1.414.jar Mekanism {mekanism@9.10.1 DONE}
		Patchouli-1.15.2-1.2-31.jar Patchouli {patchouli@1.15.2-1.2-30 DONE}
		Xaeros_Minimap_20.7.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.7.1 DONE}
		JAOPCA-1.15.2-3.2.0.9.jar JAOPCA {jaopca@3.2.0.9 DONE}
		ForgeEndertech-1.15.2-6.0.2.2-build.0030.jar Forge Endertech {forgeendertech@6.0.2.2 DONE}
		AdLods-1.15.2-3.0.3.0-build.0035.jar Large Ore Deposits {adlods@3.0.3.0 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		XaerosWorldMap_1.5.7_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.7 DONE}
		OresAboveDiamonds+1.15+v3.3.jar Ores Above Diamonds {oresabovediamonds@3.2 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		PyramidPlunder-1.15.2-1.0.jar Pyramid Plunder {pyramidplunder@1.15-1.0 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		structurize-0.10.305-ALPHA.jar Structurize {structurize@0.10.305-ALPHA DONE}
		guardvillagers-1.15.2-1.0.6.jar Guard Villagers {guardvillagers@1.0.6 DONE}
		minecolonies-0.11.886-BETA-universal.jar Minecolonies {minecolonies@0.11.886-BETA DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		forge-1.15.2-31.1.50-universal.jar Forge {forge@31.1.50 DONE}
		Aquaculture-1.15.2-2.0.13.jar Aquaculture 2 {aquaculture@1.15.2-2.0.13 DONE}
		Ma-Essentials-1.15.2-3.0.3.jar Ma Essentials {ma-essentials@1.15.2-3.0.3 DONE}
		refinedstorage-1.8.2.jar Refined Storage {refinedstorage@1.8.2 DONE}
		corpse-1.15.2-1.0.3.jar Corpse {corpse@1.15.2-1.0.3 DONE}
	Launched Version: 1.15.2-forge-31.1.50
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz

**Comment by SaemonMoki** [comment]
This should be fixed in the latest release. Please download our 0.5.3 version.
