### ISSUE TITLE
1.14.4 -  NullPointerException: Colliding entity with block

### ISSUE THREAD

**Issue by sixtymillionsqrd** [SaemonMoki/ExtendedAnimals#33]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 5/1/20 6:13 PM
Description: Colliding entity with block

java.lang.NullPointerException: Colliding entity with block
	at mokiyoki.enhancedanimals.loot.EnhancedChickenLootCondition.test(EnhancedChickenLootCondition.java:21) ~[?:0.4.11] {re:classloading}
	at mokiyoki.enhancedanimals.loot.EnhancedChickenLootCondition.test(EnhancedChickenLootCondition.java:16) ~[?:0.4.11] {re:classloading}
	at net.minecraft.world.storage.loot.LootPool.func_216091_a(LootPool.java:87) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.storage.loot.LootTable.func_216114_a(LootTable.java:70) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.loot.LootTable.func_216120_b(LootTable.java:82) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.loot.LootTable.func_216113_a(LootTable.java:87) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_213354_a(LivingEntity.java:1173) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_213354_a(MobEntity.java:426) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_213345_d(LivingEntity.java:1147) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70645_a(LivingEntity.java:1115) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:973) ~[?:?] {re:classloading}
	at net.minecraft.entity.passive.AnimalEntity.func_70097_a(SourceFile:67) ~[?:?] {re:classloading}
	at com.matez.wildnature.blocks.PoisonIvyBlock.func_196262_a(PoisonIvyBlock.java:33) ~[?:2.1.6.5] {re:classloading}
	at net.minecraft.block.BlockState.func_196950_a(BlockState.java:262) ~[?:?] {re:classloading}
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:838) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:572) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:1830) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2215) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:460) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:140) ~[?:?] {re:classloading}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(SourceFile:44) ~[?:?] {re:classloading}
	at mokiyoki.enhancedanimals.entity.EnhancedChicken.func_70636_d(EnhancedChicken.java:512) ~[?:0.4.11] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2033) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld$$Lambda$5879/1149208598.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:766) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mokiyoki.enhancedanimals.loot.EnhancedChickenLootCondition.test(EnhancedChickenLootCondition.java:21)
	at mokiyoki.enhancedanimals.loot.EnhancedChickenLootCondition.test(EnhancedChickenLootCondition.java:16)
	at net.minecraft.world.storage.loot.LootPool.func_216091_a(LootPool.java:87)
	at net.minecraft.world.storage.loot.LootTable.func_216114_a(LootTable.java:70)
	at net.minecraft.world.storage.loot.LootTable.func_216120_b(LootTable.java:82)
	at net.minecraft.world.storage.loot.LootTable.func_216113_a(LootTable.java:87)
	at net.minecraft.entity.LivingEntity.func_213354_a(LivingEntity.java:1173)
	at net.minecraft.entity.MobEntity.func_213354_a(MobEntity.java:426)
	at net.minecraft.entity.LivingEntity.func_213345_d(LivingEntity.java:1147)
	at net.minecraft.entity.LivingEntity.func_70645_a(LivingEntity.java:1115)
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:973)
	at net.minecraft.entity.passive.AnimalEntity.func_70097_a(SourceFile:67)
	at com.matez.wildnature.blocks.PoisonIvyBlock.func_196262_a(PoisonIvyBlock.java:33)
	at net.minecraft.block.BlockState.func_196950_a(BlockState.java:262)

-- Block being collided with --
Details:
	Block: Block{wildnature:poison_ivy}[flowering=true]
	Block location: World: (411,73,-9), Chunk: (at 11,4,7 in 25,-1; contains blocks 400,0,-16 to 415,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:838)

-- Entity being checked for collision --
Details:
	Entity Type: eanimod:enhanced_chicken (mokiyoki.enhancedanimals.entity.EnhancedChicken)
	Entity ID: 1678
	Entity Name: Chicken
	Entity's Exact location: 411.51, 73.00, -9.01
	Entity's Block location: World: (411,73,-10), Chunk: (at 11,4,6 in 25,-1; contains blocks 400,0,-16 to 415,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:572)
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:1830)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2215)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:460)
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:140)
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(SourceFile:44)
	at mokiyoki.enhancedanimals.entity.EnhancedChicken.func_70636_d(EnhancedChicken.java:512)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2033)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587)
	at net.minecraft.world.server.ServerWorld$$Lambda$5879/1149208598.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: eanimod:enhanced_chicken (mokiyoki.enhancedanimals.entity.EnhancedChicken)
	Entity ID: 1678
	Entity Name: Chicken
	Entity's Exact location: 411.51, 73.00, -9.01
	Entity's Block location: World: (411,73,-10), Chunk: (at 11,4,6 in 25,-1; contains blocks 400,0,-16 to 415,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['SixtyMillionSqrd'/208, l='New World', x=395.47, y=71.86, z=4.75]]
	Chunk stats: ServerChunkCache: 3105
	Level dimension: DimensionType{minecraft:overworld}
	Level name: New World
	Level seed: 3354078896626309919
	Level generator: ID 07 - wildnature, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1513 game time, 1513 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 19162 (now: false), thunder time: 117663 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:766)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2229722992 bytes (2126 MB) / 3762290688 bytes (3588 MB) up to 7492075520 bytes (7145 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8037m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.6.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.6.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.6.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.6.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.6.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.6
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.6-client.jar Minecraft {minecraft@1.14.4 DONE}
		pamhc2trees-1.14.4-1.0.0.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		pamhc2crops-1.14.4-1.0.4.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		seafaring-1.14.4-0.2.2.jar Seafaring {sea@0.2.2 DONE}
		earthsanimals-1.14.4-0.0.5-beta.jar Earths Animals {earthsanimals@1.14.4-0.0.4-beta DONE}
		voyage-1.0.0.jar Voyage {voyage@1.0.0 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		Druidcraft-1.14-0.3.1.jar Druidcraft {druidcraft@0.3.1 DONE}
		GeneticAnimals_0_4_13.jar Genetic Animals {eanimod@0.4.11 DONE}
		wildnature-2.1.6.5.jar WildNature {wildnature@2.1.6.5 DONE}
		forge-1.14.4-28.2.6-universal.jar Forge {forge@28.2.6 DONE}
		Upgrade-Aquatic-1.14.4-v1.4.10.jar Upgrade Aquatic {upgrade_aquatic@1.4.9 DONE}
		More Dogs-1.0.3.jar More Dog Breeds {moredogs@1.0.3 DONE}
		pamhc2foodcore-1.14.4-1.0.3.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		autumnity-1.0.0-1.14.4.jar Autumnity {autumnity@1.0.0 DONE}
		horse_colors-1.14.4-1.1.0.jar Realistic Horse Genetics {horse_colors@1.14.4-1.1.0 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['SixtyMillionSqrd'/208, l='New World', x=395.47, y=71.86, z=4.75]]
	Data Packs: vanilla, mod:autumnity, mod:druidcraft, mod:eanimod, mod:earthsanimals, mod:forge, mod:horse_colors, mod:jei, mod:moredogs, mod:pamhc2crops, mod:pamhc2foodcore, mod:pamhc2trees, mod:sea, mod:upgrade_aquatic, mod:voyage, mod:wildnature
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by HerrBeef** [comment]
I've the same problem

**Comment by SaemonMoki** [comment]
Duplicate, and was fixed.
