### ISSUE TITLE
1.15.2-31.1.74[mobs affected by mod dont spawn] [mobs affected: chicken,pigs,sheep,rabbit,llama]

### ISSUE THREAD

**Issue by SDUBZ** [SaemonMoki/ExtendedAnimals#34]
GeneticAnimals-0_5_4

forge: 1.15.2-31.1.74

so far its cows and chickens
from testing

**Comment by SDUBZ** [comment]
Error executing task on Client
java.lang.IllegalStateException: No renderer registered for eanimod:enhanced_cat
	at net.minecraft.client.renderer.entity.EntityRendererManager.validateRendererExistence(EntityRendererManager.java:192)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:50)
	at net.minecraftforge.fml.client.ClientModLoader.postSidedRunnable(ClientModLoader.java:127)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$10624/1576698743.accept(Unknown Source)
	at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:160)
	at net.minecraftforge.fml.ModLoader$$Lambda$13651/618317976.run(Unknown Source)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader$$Lambda$12856/1553566061.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:897)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$478/488372159.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by SDUBZ** [comment]
heres a log to help find out whats causing mobs from vanilla spawn eggs to not work with mod
log: 
[latest.log](https://github.com/SaemonMoki/ExtendedAnimals/files/4580321/latest.log)

**Comment by SaemonMoki** [comment]
I'm a little bit confused. Are you saying vanilla mobs don't spawn? Or our mobs don't spawn? Or both?

**Comment by SDUBZ** [comment]
yes the vanilla versions are not spawning you hear the sound of animal but its like they are invisible when spawned via eggs

**Comment by SaemonMoki** [comment]
That's strange. But vanilla versions only spawn if you have the config enabled. They do not spawn normally. In our mod's config file, you'll see config such as: "doSpawnVanillaChicken" and such. Turn those to True and they will spawn again.
