### ISSUE TITLE
Genetic Animals incompatibility with Atum 2 causes ticking entity crash

### ISSUE THREAD

**Issue by BeanZephyron** [SaemonMoki/ExtendedAnimals#76]
I kept receiving a ticking entity crash when using this mod with Atum 2. The crashes happen every time that a villager tries to spawn into the game.

**Comment by CREEATION** [comment]
Came here to give some more context with a crash log.

```js
[20Mai2021 14:46:09.091] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: HIGHEST
		1: ASM: mokiyoki.enhancedanimals.util.handlers.EventSubscriber@58bed55c onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		2: NORMAL
		3: ASM: class org.orecruncher.lib.effects.EntityEffectHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		4: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem holdingExtendoGripIncreasesRange(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		5: ASM: class com.teammetallurgy.atum.items.artifacts.atem.AtemsProtectionItem onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		6: ASM: class com.simibubi.create.events.CommonEvents onUpdateLivingEntity(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		7: ASM: class com.teammetallurgy.atum.items.tools.HammerItem livingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		8: ASM: vazkii.quark.content.tweaks.module.DragonScalesModule@175df48f onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		9: ASM: vazkii.quark.content.tweaks.module.PoisonPotatoUsageModule@7197f93c onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		10: ASM: vazkii.quark.content.world.module.BiotiteModule@1e250607 onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		11: ASM: tschipp.carryon.common.event.ItemEvents@52b83921 dropNonHotbarItems(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		12: ASM: top.theillusivec4.champions.common.ChampionEventsHandler@6b0d9bd0 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		13: ASM: tschipp.carryon.common.event.ItemEntityEvents@158050dc onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		14: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@2734e270 tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		15: ASM: squeek.appleskin.network.SyncHandler@700e71f9 onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
java.lang.NullPointerException
	at mokiyoki.enhancedanimals.util.handlers.EventSubscriber.onLivingUpdateEvent(EventSubscriber.java:134)
	at net.minecraftforge.eventbus.ASMEventHandler_154_EventSubscriber_onLivingUpdateEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:339)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431)
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70071_h_(VillagerEntity.java:234)
	at com.teammetallurgy.atum.entity.villager.AtumVillagerEntity.func_70071_h_(AtumVillagerEntity.java:268)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.lang.Thread.run(Thread.java:748)

[20Mai2021 14:46:09.094] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID ff720375-c790-4f59-ab22-268dafb2f9da
[20Mai2021 14:46:09.098] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
	at mokiyoki.enhancedanimals.util.handlers.EventSubscriber.onLivingUpdateEvent(EventSubscriber.java:134) ~[eanimod:0_6_29]
	at net.minecraftforge.eventbus.ASMEventHandler_154_EventSubscriber_onLivingUpdateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:339) ~[forge:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431) ~[?:?]
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70071_h_(VillagerEntity.java:234) ~[?:?]
	at com.teammetallurgy.atum.entity.villager.AtumVillagerEntity.func_70071_h_(AtumVillagerEntity.java:268) ~[atum:1.16.5-2.2.3]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more

```

**Comment by SaemonMoki** [comment]
The upcoming bug release has a workaround for this, however it is caused because Atum sometimes returns null for a villager's profession, which they should definitely fix there side too.
